image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - pip install poetry
    - poetry install
    - python -m flake8
    - python -m isort --check .
    - python -m black --check .
    - python -m mypy .
    - pytest

build package:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - pip install build twine
    - python -m build --sdist
    - twine check dist/*
  artifacts:
    paths:
      - dist/*

publish package:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          && $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-?.*$/
  needs:
    - job: build package
  script:
    - twine check dist/*
    - twine upload dist/*

build docs:
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - pip install sphinx sphinx-rtd-theme
    - ( cd doc && make html )
    - mv build/html built-docs
  artifacts:
    paths:
      - built-docs

pages:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          && $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+-?.*$/
  needs:
    - job: build docs
  script:
    - mv built-docs public
